---
running_model:
  class: IntegratedActionModelEuler
  differential:
    class: DifferentialActionModelFreeFwdDynamics
    costs:
      - name: control_reg
        update: true
        weight: 1.0
        active: true
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelControl
      - name: state_reg
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelState

terminal_model:
  class: IntegratedActionModelEuler
  differential:
    class: DifferentialActionModelFreeFwdDynamics
    costs:
      - name: state_reg
        update: true
        weight: 0.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelState
